export const activityValues = [
  'SURF',
  'MTB',
  'SKATEBOARDING',
  'RUNNING_ROAD',
  'RUNNING_TRAIL',
  'CYCLING_ROAD',
  'CYCLING_GRAVEL',
  'BMX',
  'TRIATHLON',
  'OPEN_WATER_SWIMMING',
  'SKI_ALPINE',
  'SNOWBOARD',
  'SKI_CROSS_COUNTRY',
  'CLIMBING_BOULDER',
  'HIKING',
  'OTHER',
] as const;

export const activityOptions = [
  { value: 'SURF', label: 'Surf' },
  { value: 'MTB', label: 'Mountain Bike' },
  { value: 'SKATEBOARDING', label: 'Skateboarding' },
  { value: 'RUNNING_ROAD', label: 'Running (Road)' },
  { value: 'RUNNING_TRAIL', label: 'Running (Trail)' },
  { value: 'CYCLING_ROAD', label: 'Cycling (Road)' },
  { value: 'CYCLING_GRAVEL', label: 'Cycling (Gravel)' },
  { value: 'BMX', label: 'BMX' },
  { value: 'TRIATHLON', label: 'Triathlon' },
  { value: 'OPEN_WATER_SWIMMING', label: 'Open Water Swimming' },
  { value: 'SKI_ALPINE', label: 'Ski (Alpine)' },
  { value: 'SNOWBOARD', label: 'Snowboard' },
  { value: 'SKI_CROSS_COUNTRY', label: 'Ski (XC)' },
  { value: 'CLIMBING_BOULDER', label: 'Climbing/Bouldering' },
  { value: 'HIKING', label: 'Hiking' },
  { value: 'OTHER', label: 'Other' },
] as const;
